# Generated by Django 2.0.5 on 2018-06-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('idcountry', models.IntegerField(db_column='idCountry', primary_key=True, serialize=False)),
                ('countryname', models.CharField(db_column='Countryname', max_length=45)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('idmember', models.IntegerField(db_column='idMember', primary_key=True, serialize=False)),
                ('membername', models.CharField(db_column='Membername', max_length=45)),
                ('memberemail', models.CharField(db_column='MemberEmail', max_length=45)),
                ('memberpassword', models.CharField(db_column='MemberPassword', max_length=45)),
                ('memberbday', models.DateField(db_column='MemberBday')),
                ('membergender', models.CharField(db_column='MemberGender', max_length=2)),
                ('memberhobby', models.CharField(blank=True, db_column='MemberHobby', max_length=45, null=True)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idregion', models.IntegerField(db_column='idRegion', primary_key=True, serialize=False)),
                ('regionname', models.CharField(db_column='Regionname', max_length=45)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
    ]
